// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALFUIyYHVTFU112k1n6aXYUgDwDOdonBQ',
    appId: '1:602961898702:web:7768288d3cbda0158d349f',
    messagingSenderId: '602961898702',
    projectId: 'wtf-flutter-test-52880',
    authDomain: 'wtf-flutter-test-52880.firebaseapp.com',
    storageBucket: 'wtf-flutter-test-52880.firebasestorage.app',
    measurementId: 'G-LX16JR38WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh6Fx4D8vSfdW-AndpsS_9RuyR0rT1NoY',
    appId: '1:602961898702:android:bb008c6c34e153468d349f',
    messagingSenderId: '602961898702',
    projectId: 'wtf-flutter-test-52880',
    storageBucket: 'wtf-flutter-test-52880.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPd-TZMHa_lAHiuABZL5w-FP4f5c1afLg',
    appId: '1:602961898702:ios:cf756702f191aa088d349f',
    messagingSenderId: '602961898702',
    projectId: 'wtf-flutter-test-52880',
    storageBucket: 'wtf-flutter-test-52880.firebasestorage.app',
    iosBundleId: 'com.example.guruApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPd-TZMHa_lAHiuABZL5w-FP4f5c1afLg',
    appId: '1:602961898702:ios:cf756702f191aa088d349f',
    messagingSenderId: '602961898702',
    projectId: 'wtf-flutter-test-52880',
    storageBucket: 'wtf-flutter-test-52880.firebasestorage.app',
    iosBundleId: 'com.example.guruApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALFUIyYHVTFU112k1n6aXYUgDwDOdonBQ',
    appId: '1:602961898702:web:d31bc45113d60cac8d349f',
    messagingSenderId: '602961898702',
    projectId: 'wtf-flutter-test-52880',
    authDomain: 'wtf-flutter-test-52880.firebaseapp.com',
    storageBucket: 'wtf-flutter-test-52880.firebasestorage.app',
    measurementId: 'G-MSYMWWBWGW',
  );
}
